/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "If you would like to speedrun this, press Play Again and record your attempt, then submit on the Discord Server in the channel #speedrun-submissions.": "如果您想加速运行，请按再次播放并记录您的尝试，然后在频道#speedrun-submissions 的 Discord 服务器上提交。",
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    "Main Prestige Tree Discord": "主声望树 Discord",
    "Make sure that you record the time in your stream or else your speedrun won't count!": "确保您在流中记录时间，否则您的速通将不计入！",
    "Note by Jacorb: If anyone wishes to make a mod of this game, that is perfectly fine with me, just make sure to name it something different (ex: Prestige Tree NG+) and to let me know on": "Jacorb 的笔记：如果有人想制作这款游戏的模组，这对我来说完全没有问题，只需确保将其命名为不同的名称（例如：Prestige Tree NG+）并让我知道",
    "Oh, you are still reading this?": "哦，你还在读这个吗？",
    "Original idea by papyrus (on discord)": "原创想法来自papyrus（在discord）",
    "Please check the Discord to see there are new content updates!": "请检查 Discord 以查看有新的内容更新！",
    "embers": "余烬",
    "Your best {{tmp[layer].resource}} is {{formatWhole(player[layer].best)}}": "你最佳 {{tmp[layer].resource}} 是 {{formatWhole(player[layer].best)}}",
    "ashes": "灰烬",
    "The flame now affects your ash gain.": "火焰现在会影响你的灰烬增益。",
    "The flame loses strength at half the rate.": "火焰以一半的速度失去强度。",
    "The flame's effect is stronger based on your ashes.": "根据你的灰烬，火焰的效果会更强。",
    "The flame loses strength slower based on your ashes.": "根据你的灰烬，火焰失去力量的速度较慢。",
    "自动保存: {{ player.autosave?\"ON\":\"OFF\" }}": "自动保存: {{ player.autosave?\"开启\":\"关闭\" }}",
    "完成的挑战: {{ player.hideChallenges?\"HIDDEN\":\"SHOWN\" }}": "完成的挑战: {{ player.hideChallenges?\"隐藏\":\"显示\" }}",
    "高质量树贴图: {{ player.hqTree?\"ON\":\"OFF\" }}": "高质量树贴图: {{ player.hqTree?\"开启\":\"关闭\" }}",
    "离线生产: {{ player.offlineProd?\"ON\":\"OFF\" }}": "离线生产: {{ player.offlineProd?\"开启\":\"关闭\" }}",
    "electricity": "电力",
    "Unlock a new column of ash upgrades": "解锁新的灰烬升级列",
    "You keep ash upgrades on electricity reset": "你在电力重置时保留灰烬升级",
    "The flame's effect boosts ember gain even more.": "火焰的效果会进一步提高余烬增益。",
    "You gain more embers based on your ashes.": "你会根据你的灰烬获得更多的余烬。",
    "The flame's effect is stronger based on your embers.": "根据你的余烬，火焰的效果会更强。",
    "You can buy max coal": "您可以购买最大煤",
    "You can now automatically do an ash reset when your flame strength drops below 10": "当你的火焰强度低于 10 时，你现在可以自动进行灰烬重置",
    "You gain more ashes based on your embers.": "你会根据你的余烬获得更多的灰烬。",
    "You keep ash upgrades on coal reset": "您在煤炭重置时保留灰烬升级",
    "Your ash gain is boosted by your coal.": "你的灰烬增益基于你的煤。",
    "coal": "煤",
    "The flame's effect boosts coal's effect.": "火焰的效果会增强煤炭的效果。",
    "The flame's effect is impacted less by the flame's strength.": "火焰的效果受火焰强度的影响较小。",
    "Your coal boosts your ember gain.": "你的煤炭会增加你的余烬收益。",
    "a: reset your embers for ashes": "a：将你的余烬重置为灰烬",
    "显示里程碑: Default": "显示里程碑: 默认",
    "主题: Default": "主题: 默认",
    "主题: AUTOMATION": "主题: 自动",
    "主题: INCOMPLETE": "主题: 未完成",
    "主题: ALWAYS": "主题: 一直",
    "显示里程碑: AUTOMATION": "显示里程碑: 自动",
    "显示里程碑: INCOMPLETE": "显示里程碑: 未完成",
    "显示里程碑: ALWAYS": "显示里程碑: 一直",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "my discord": "my discord",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played:": "已玩时长：",
    "Flame Strength: ": "火焰强度：",
    "Dev Speed: ": "开发速度: ",
    "You have made a total of ": "你总共做了",
    "You have ": "你有 ",
    "Boost flame effect (": "提高 火焰 效果（",
    "Boost flame gain (": "提高 火焰 增益（",
    "Boost ember gain (": "提高 余烬 增益（",
    "Boost ash gain (": "提高 灰烬 增益（",
    "Electricity allocated: ": "电力分配：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\/([\d\.]+)$/,
    /^离线时间: ([\d\.]+)s$/,
    /^火焰强度：([\d\.]+)$/,
    /^已玩时长：(.+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^, providing (.+) strength to allocated electricity.$/, '，为分配的电力提供 $1 的强度。'],
    [/^, boosting the flame effect by (.+)$/, ', 将火焰效果提升 $1'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) embers$/, '下一个在 $1 余烬'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) coal$/, '$1 煤'],
    [/^([\d\.]+) electricity$/, '$1 电力'],
    [/^([\d\.]+) embers.$/, '$1 余烬。'],
    [/^([\d\.,]+) embers.$/, '$1 余烬。'],
    [/^([\d\.,]+) coal$/, '$1 煤'],
    [/^([\d\.]+)e([\d\.,]+) embers.$/, '$1e$2 余烬。'],
    [/^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+) embers$/, '$1e$2 \/ $3e$4余烬。'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) coal$/, '成本：$1 煤'],
    [/^Cost: (.+) ashes$/, '成本：$1 灰烬'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Next: (.+) \/ (.+) embers$/, '下一个：$1 \/ $2 余烬'],
    [/^(.+) \/ ([\d\.]+)e([\d\.,]+) embers$/, '$1 \/ $3e$4 余烬。'],
    [/^Req: (.+) \/ (.+) embers$/, '成本：$1 \/ $2 余烬'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);